version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-10

    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-10

    # db mysql
    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-10
    #phpmyadmin
    db-phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:apache
        container_name: db-phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_HOST: db
            UPLOAD_LIMIT: 256M
        networks:
            - laravel-10

    # queue
    queue:
        image: especializati/laravel9-app
        container_name: queue
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-10

    # redis
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - laravel-10

networks:
    laravel-10:
        driver: bridge
